<?php

/* Para gerar este arquivo, execute 'php artisan app:db-export'
Para criar tabelas e colunas, execute 'php artisan app:db-import' */

return [
  'tables' => [
    'emails' => [
      'Name' => 'emails',
      'Engine' => 'InnoDB',
      'Auto_increment' => NULL,
      'Collation' => 'utf8_unicode_ci',
      'Comment' => '',
      'Model' => 'Emails',
      'ModelNamespace' => '\\App\\Models',
      'ModelFile' => '\\app\\Models\\Emails.php',
      'Controller' => 'EmailsController',
      'ControllerNamespace' => '\\App\\Http\\Controllers',
      'ControllerFile' => '\\app\\Http\\Controllers\\EmailsController.php',
      'Sql' => 'CREATE TABLE IF NOT EXISTS `emails` (  `id` int(11) NOT NULL,  `from` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,  `to` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,  `subject` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,  `body` text COLLATE utf8_unicode_ci,  `created_at` timestamp NULL DEFAULT NULL,  `updated_at` timestamp NULL DEFAULT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
      'Fields' => [
        'id' => [
          'Field' => 'id',
          'Type' => 'int(11)',
          'Null' => 'NO',
          'Key' => 'PRI',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'int(11) NOT NULL',
        ],
        'from' => [
          'Field' => 'from',
          'Type' => 'varchar(500)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(500) NULL',
        ],
        'to' => [
          'Field' => 'to',
          'Type' => 'varchar(500)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(500) NULL',
        ],
        'subject' => [
          'Field' => 'subject',
          'Type' => 'varchar(255)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NULL',
        ],
        'body' => [
          'Field' => 'body',
          'Type' => 'text',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'text NULL DEFAULT NULL',
        ],
        'created_at' => [
          'Field' => 'created_at',
          'Type' => 'timestamp',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'timestamp NULL',
        ],
        'updated_at' => [
          'Field' => 'updated_at',
          'Type' => 'timestamp',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'timestamp NULL',
        ],
      ],
    ],
    'failed_jobs' => [
      'Name' => 'failed_jobs',
      'Engine' => 'InnoDB',
      'Auto_increment' => 1,
      'Collation' => 'utf8_unicode_ci',
      'Comment' => '',
      'Model' => 'FailedJobs',
      'ModelNamespace' => '\\App\\Models',
      'ModelFile' => '\\app\\Models\\FailedJobs.php',
      'Controller' => 'FailedJobsController',
      'ControllerNamespace' => '\\App\\Http\\Controllers',
      'ControllerFile' => '\\app\\Http\\Controllers\\FailedJobsController.php',
      'Sql' => 'CREATE TABLE IF NOT EXISTS `failed_jobs` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `uuid` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,  `connection` text COLLATE utf8_unicode_ci,  `queue` text COLLATE utf8_unicode_ci,  `payload` longtext COLLATE utf8_unicode_ci NOT NULL,  `exception` longtext COLLATE utf8_unicode_ci NOT NULL,  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
      'Fields' => [
        'id' => [
          'Field' => 'id',
          'Type' => 'bigint(20) unsigned',
          'Null' => 'NO',
          'Key' => 'PRI',
          'Default' => NULL,
          'Extra' => 'auto_increment',
          'Sql' => 'bigint(20) unsigned NOT NULL AUTO_INCREMENT',
        ],
        'uuid' => [
          'Field' => 'uuid',
          'Type' => 'varchar(255)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NULL',
        ],
        'connection' => [
          'Field' => 'connection',
          'Type' => 'text',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'text NULL DEFAULT NULL',
        ],
        'queue' => [
          'Field' => 'queue',
          'Type' => 'text',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'text NULL DEFAULT NULL',
        ],
        'payload' => [
          'Field' => 'payload',
          'Type' => 'longtext',
          'Null' => 'NO',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'longtext NOT NULL',
        ],
        'exception' => [
          'Field' => 'exception',
          'Type' => 'longtext',
          'Null' => 'NO',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'longtext NOT NULL',
        ],
        'failed_at' => [
          'Field' => 'failed_at',
          'Type' => 'timestamp',
          'Null' => 'NO',
          'Key' => '',
          'Default' => 'CURRENT_TIMESTAMP',
          'Extra' => '',
          'Sql' => 'timestamp NOT NULL',
        ],
      ],
    ],
    'files' => [
      'Name' => 'files',
      'Engine' => 'InnoDB',
      'Auto_increment' => 21,
      'Collation' => 'utf8_unicode_ci',
      'Comment' => '',
      'Model' => 'Files',
      'ModelNamespace' => '\\App\\Models',
      'ModelFile' => '\\app\\Models\\Files.php',
      'Controller' => 'FilesController',
      'ControllerNamespace' => '\\App\\Http\\Controllers',
      'ControllerFile' => '\\app\\Http\\Controllers\\FilesController.php',
      'Sql' => 'CREATE TABLE IF NOT EXISTS `files` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT \'\',  `slug` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT \'\',  `mime` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT \'\',  `ext` varchar(5) COLLATE utf8_unicode_ci NOT NULL DEFAULT \'\',  `size` int(11) DEFAULT NULL,  `folder` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT \'\',  `url` text COLLATE utf8_unicode_ci NOT NULL,  `base64` longtext COLLATE utf8_unicode_ci,  `created_at` datetime DEFAULT NULL,  `updated_at` datetime DEFAULT NULL,  `deleted_at` datetime DEFAULT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
      'Fields' => [
        'id' => [
          'Field' => 'id',
          'Type' => 'bigint(20) unsigned',
          'Null' => 'NO',
          'Key' => 'PRI',
          'Default' => NULL,
          'Extra' => 'auto_increment',
          'Sql' => 'bigint(20) unsigned NOT NULL AUTO_INCREMENT',
        ],
        'name' => [
          'Field' => 'name',
          'Type' => 'varchar(255)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => '',
          'Extra' => '',
          'Sql' => 'varchar(255) NOT NULL',
        ],
        'slug' => [
          'Field' => 'slug',
          'Type' => 'varchar(255)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => '',
          'Extra' => '',
          'Sql' => 'varchar(255) NOT NULL',
        ],
        'mime' => [
          'Field' => 'mime',
          'Type' => 'varchar(50)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => '',
          'Extra' => '',
          'Sql' => 'varchar(50) NOT NULL',
        ],
        'ext' => [
          'Field' => 'ext',
          'Type' => 'varchar(5)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => '',
          'Extra' => '',
          'Sql' => 'varchar(5) NOT NULL',
        ],
        'size' => [
          'Field' => 'size',
          'Type' => 'int(11)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'int(11) NULL',
        ],
        'folder' => [
          'Field' => 'folder',
          'Type' => 'varchar(255)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => '',
          'Extra' => '',
          'Sql' => 'varchar(255) NOT NULL',
        ],
        'url' => [
          'Field' => 'url',
          'Type' => 'text',
          'Null' => 'NO',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'text NOT NULL DEFAULT NULL',
        ],
        'base64' => [
          'Field' => 'base64',
          'Type' => 'longtext',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'longtext NULL',
        ],
        'created_at' => [
          'Field' => 'created_at',
          'Type' => 'datetime',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'datetime NULL DEFAULT NULL',
        ],
        'updated_at' => [
          'Field' => 'updated_at',
          'Type' => 'datetime',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'datetime NULL DEFAULT NULL',
        ],
        'deleted_at' => [
          'Field' => 'deleted_at',
          'Type' => 'datetime',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'datetime NULL DEFAULT NULL',
        ],
      ],
    ],
    'migrations' => [
      'Name' => 'migrations',
      'Engine' => 'InnoDB',
      'Auto_increment' => 9,
      'Collation' => 'utf8_unicode_ci',
      'Comment' => '',
      'Model' => 'Migrations',
      'ModelNamespace' => '\\App\\Models',
      'ModelFile' => '\\app\\Models\\Migrations.php',
      'Controller' => 'MigrationsController',
      'ControllerNamespace' => '\\App\\Http\\Controllers',
      'ControllerFile' => '\\app\\Http\\Controllers\\MigrationsController.php',
      'Sql' => 'CREATE TABLE IF NOT EXISTS `migrations` (  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,  `migration` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `batch` int(11) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
      'Fields' => [
        'id' => [
          'Field' => 'id',
          'Type' => 'int(10) unsigned',
          'Null' => 'NO',
          'Key' => 'PRI',
          'Default' => NULL,
          'Extra' => 'auto_increment',
          'Sql' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ],
        'migration' => [
          'Field' => 'migration',
          'Type' => 'varchar(255)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NOT NULL',
        ],
        'batch' => [
          'Field' => 'batch',
          'Type' => 'int(11)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'int(11) NOT NULL',
        ],
      ],
    ],
    'oauth_providers' => [
      'Name' => 'oauth_providers',
      'Engine' => 'InnoDB',
      'Auto_increment' => 1,
      'Collation' => 'utf8mb4_unicode_ci',
      'Comment' => '',
      'Model' => 'OauthProviders',
      'ModelNamespace' => '\\App\\Models',
      'ModelFile' => '\\app\\Models\\OauthProviders.php',
      'Controller' => 'OauthProvidersController',
      'ControllerNamespace' => '\\App\\Http\\Controllers',
      'ControllerFile' => '\\app\\Http\\Controllers\\OauthProvidersController.php',
      'Sql' => 'CREATE TABLE IF NOT EXISTS `oauth_providers` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `user_id` bigint(20) unsigned NOT NULL,  `provider` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,  `provider_user_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,  `access_token` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  `refresh_token` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  `created_at` timestamp NULL DEFAULT NULL,  `updated_at` timestamp NULL DEFAULT NULL,  PRIMARY KEY (`id`),  KEY `oauth_providers_user_id_foreign` (`user_id`),  KEY `oauth_providers_provider_user_id_index` (`provider_user_id`),  CONSTRAINT `oauth_providers_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
      'Fields' => [
        'id' => [
          'Field' => 'id',
          'Type' => 'bigint(20) unsigned',
          'Null' => 'NO',
          'Key' => 'PRI',
          'Default' => NULL,
          'Extra' => 'auto_increment',
          'Sql' => 'bigint(20) unsigned NOT NULL AUTO_INCREMENT',
        ],
        'user_id' => [
          'Field' => 'user_id',
          'Type' => 'bigint(20) unsigned',
          'Null' => 'NO',
          'Key' => 'MUL',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'bigint(20) unsigned NOT NULL',
        ],
        'provider' => [
          'Field' => 'provider',
          'Type' => 'varchar(255)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NOT NULL',
        ],
        'provider_user_id' => [
          'Field' => 'provider_user_id',
          'Type' => 'varchar(255)',
          'Null' => 'NO',
          'Key' => 'MUL',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NOT NULL',
        ],
        'access_token' => [
          'Field' => 'access_token',
          'Type' => 'varchar(255)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NULL',
        ],
        'refresh_token' => [
          'Field' => 'refresh_token',
          'Type' => 'varchar(255)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NULL',
        ],
        'created_at' => [
          'Field' => 'created_at',
          'Type' => 'timestamp',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'timestamp NULL',
        ],
        'updated_at' => [
          'Field' => 'updated_at',
          'Type' => 'timestamp',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'timestamp NULL',
        ],
      ],
    ],
    'pages' => [
      'Name' => 'pages',
      'Engine' => 'InnoDB',
      'Auto_increment' => 13,
      'Collation' => 'utf8_unicode_ci',
      'Comment' => '',
      'Model' => 'Pages',
      'ModelNamespace' => '\\App\\Models',
      'ModelFile' => '\\app\\Models\\Pages.php',
      'Controller' => 'PagesController',
      'ControllerNamespace' => '\\App\\Http\\Controllers',
      'ControllerFile' => '\\app\\Http\\Controllers\\PagesController.php',
      'Sql' => 'CREATE TABLE IF NOT EXISTS `pages` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `slug` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,  `status` varchar(50) COLLATE utf8_unicode_ci DEFAULT \'publish\',  `content` text COLLATE utf8_unicode_ci,  `created_at` datetime DEFAULT NULL,  `updated_at` datetime DEFAULT NULL,  `deleted_at` datetime DEFAULT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
      'Fields' => [
        'id' => [
          'Field' => 'id',
          'Type' => 'bigint(20) unsigned',
          'Null' => 'NO',
          'Key' => 'PRI',
          'Default' => NULL,
          'Extra' => 'auto_increment',
          'Sql' => 'bigint(20) unsigned NOT NULL AUTO_INCREMENT',
        ],
        'slug' => [
          'Field' => 'slug',
          'Type' => 'varchar(255)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NULL',
        ],
        'name' => [
          'Field' => 'name',
          'Type' => 'varchar(255)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NULL',
        ],
        'status' => [
          'Field' => 'status',
          'Type' => 'varchar(50)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => 'publish',
          'Extra' => '',
          'Sql' => 'varchar(50) NULL',
        ],
        'content' => [
          'Field' => 'content',
          'Type' => 'text',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'text NULL DEFAULT NULL',
        ],
        'created_at' => [
          'Field' => 'created_at',
          'Type' => 'datetime',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'datetime NULL DEFAULT NULL',
        ],
        'updated_at' => [
          'Field' => 'updated_at',
          'Type' => 'datetime',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'datetime NULL DEFAULT NULL',
        ],
        'deleted_at' => [
          'Field' => 'deleted_at',
          'Type' => 'datetime',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'datetime NULL DEFAULT NULL',
        ],
      ],
    ],
    'password_resets' => [
      'Name' => 'password_resets',
      'Engine' => 'InnoDB',
      'Auto_increment' => NULL,
      'Collation' => 'utf8_unicode_ci',
      'Comment' => '',
      'Model' => 'PasswordResets',
      'ModelNamespace' => '\\App\\Models',
      'ModelFile' => '\\app\\Models\\PasswordResets.php',
      'Controller' => 'PasswordResetsController',
      'ControllerNamespace' => '\\App\\Http\\Controllers',
      'ControllerFile' => '\\app\\Http\\Controllers\\PasswordResetsController.php',
      'Sql' => 'CREATE TABLE IF NOT EXISTS `password_resets` (  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `token` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `created_at` timestamp NULL DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
      'Fields' => [
        'email' => [
          'Field' => 'email',
          'Type' => 'varchar(255)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NOT NULL',
        ],
        'token' => [
          'Field' => 'token',
          'Type' => 'varchar(255)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NOT NULL',
        ],
        'created_at' => [
          'Field' => 'created_at',
          'Type' => 'timestamp',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'timestamp NULL',
        ],
      ],
    ],
    'settings' => [
      'Name' => 'settings',
      'Engine' => 'InnoDB',
      'Auto_increment' => 10,
      'Collation' => 'utf8_unicode_ci',
      'Comment' => '',
      'Model' => 'Settings',
      'ModelNamespace' => '\\App\\Models',
      'ModelFile' => '\\app\\Models\\Settings.php',
      'Controller' => 'SettingsController',
      'ControllerNamespace' => '\\App\\Http\\Controllers',
      'ControllerFile' => '\\app\\Http\\Controllers\\SettingsController.php',
      'Sql' => 'CREATE TABLE IF NOT EXISTS `settings` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT \'0\',  `value` text COLLATE utf8_unicode_ci,  `model` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,  `updated_at` datetime DEFAULT NULL,  `created_at` datetime DEFAULT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
      'Fields' => [
        'id' => [
          'Field' => 'id',
          'Type' => 'bigint(20) unsigned',
          'Null' => 'NO',
          'Key' => 'PRI',
          'Default' => NULL,
          'Extra' => 'auto_increment',
          'Sql' => 'bigint(20) unsigned NOT NULL AUTO_INCREMENT',
        ],
        'name' => [
          'Field' => 'name',
          'Type' => 'varchar(255)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => '0',
          'Extra' => '',
          'Sql' => 'varchar(255) NOT NULL',
        ],
        'value' => [
          'Field' => 'value',
          'Type' => 'text',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'text NULL DEFAULT NULL',
        ],
        'model' => [
          'Field' => 'model',
          'Type' => 'varchar(255)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NULL',
        ],
        'updated_at' => [
          'Field' => 'updated_at',
          'Type' => 'datetime',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'datetime NULL DEFAULT NULL',
        ],
        'created_at' => [
          'Field' => 'created_at',
          'Type' => 'datetime',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'datetime NULL DEFAULT NULL',
        ],
      ],
    ],
    'users' => [
      'Name' => 'users',
      'Engine' => 'InnoDB',
      'Auto_increment' => 11,
      'Collation' => 'utf8_unicode_ci',
      'Comment' => '',
      'Model' => 'Users',
      'ModelNamespace' => '\\App\\Models',
      'ModelFile' => '\\app\\Models\\Users.php',
      'Controller' => 'UsersController',
      'ControllerNamespace' => '\\App\\Http\\Controllers',
      'ControllerFile' => '\\app\\Http\\Controllers\\UsersController.php',
      'Sql' => 'CREATE TABLE IF NOT EXISTS `users` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `photo` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `email_verified_at` timestamp NULL DEFAULT NULL,  `password` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `remember_token` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,  `created_at` timestamp NULL DEFAULT NULL,  `updated_at` timestamp NULL DEFAULT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
      'Fields' => [
        'id' => [
          'Field' => 'id',
          'Type' => 'bigint(20) unsigned',
          'Null' => 'NO',
          'Key' => 'PRI',
          'Default' => NULL,
          'Extra' => 'auto_increment',
          'Sql' => 'bigint(20) unsigned NOT NULL AUTO_INCREMENT',
        ],
        'name' => [
          'Field' => 'name',
          'Type' => 'varchar(255)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NULL',
        ],
        'email' => [
          'Field' => 'email',
          'Type' => 'varchar(255)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NOT NULL',
        ],
        'photo' => [
          'Field' => 'photo',
          'Type' => 'varchar(255)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NOT NULL',
        ],
        'email_verified_at' => [
          'Field' => 'email_verified_at',
          'Type' => 'timestamp',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'timestamp NULL',
        ],
        'password' => [
          'Field' => 'password',
          'Type' => 'varchar(255)',
          'Null' => 'NO',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NOT NULL',
        ],
        'remember_token' => [
          'Field' => 'remember_token',
          'Type' => 'varchar(100)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(100) NULL',
        ],
        'created_at' => [
          'Field' => 'created_at',
          'Type' => 'timestamp',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'timestamp NULL',
        ],
        'updated_at' => [
          'Field' => 'updated_at',
          'Type' => 'timestamp',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'timestamp NULL',
        ],
      ],
    ],
    'users_notifications' => [
      'Name' => 'users_notifications',
      'Engine' => 'InnoDB',
      'Auto_increment' => 1,
      'Collation' => 'utf8_unicode_ci',
      'Comment' => '',
      'Model' => 'UsersNotifications',
      'ModelNamespace' => '\\App\\Models',
      'ModelFile' => '\\app\\Models\\UsersNotifications.php',
      'Controller' => 'UsersNotificationsController',
      'ControllerNamespace' => '\\App\\Http\\Controllers',
      'ControllerFile' => '\\app\\Http\\Controllers\\UsersNotificationsController.php',
      'Sql' => 'CREATE TABLE IF NOT EXISTS `users_notifications` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `user_id` bigint(20) unsigned NOT NULL,  `title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,  `body` text COLLATE utf8_unicode_ci,  `url` text COLLATE utf8_unicode_ci,  `image` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,  `created_at` timestamp NULL DEFAULT NULL,  `updated_at` timestamp NULL DEFAULT NULL,  `deleted_at` timestamp NULL DEFAULT NULL,  PRIMARY KEY (`id`),  KEY `FK_users_notifications_users` (`user_id`),  CONSTRAINT `FK_users_notifications_users` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
      'Fields' => [
        'id' => [
          'Field' => 'id',
          'Type' => 'int(11)',
          'Null' => 'NO',
          'Key' => 'PRI',
          'Default' => NULL,
          'Extra' => 'auto_increment',
          'Sql' => 'int(11) NOT NULL AUTO_INCREMENT',
        ],
        'user_id' => [
          'Field' => 'user_id',
          'Type' => 'bigint(20) unsigned',
          'Null' => 'NO',
          'Key' => 'MUL',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'bigint(20) unsigned NOT NULL',
        ],
        'title' => [
          'Field' => 'title',
          'Type' => 'varchar(255)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NULL',
        ],
        'body' => [
          'Field' => 'body',
          'Type' => 'text',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'text NULL DEFAULT NULL',
        ],
        'url' => [
          'Field' => 'url',
          'Type' => 'text',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'text NULL DEFAULT NULL',
        ],
        'image' => [
          'Field' => 'image',
          'Type' => 'varchar(255)',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'varchar(255) NULL',
        ],
        'created_at' => [
          'Field' => 'created_at',
          'Type' => 'timestamp',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'timestamp NULL',
        ],
        'updated_at' => [
          'Field' => 'updated_at',
          'Type' => 'timestamp',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'timestamp NULL',
        ],
        'deleted_at' => [
          'Field' => 'deleted_at',
          'Type' => 'timestamp',
          'Null' => 'YES',
          'Key' => '',
          'Default' => NULL,
          'Extra' => '',
          'Sql' => 'timestamp NULL',
        ],
      ],
    ],
  ],
  'fks' => [],
];